# Generated by Django 4.2.8 on 2025-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
